window.webAdminMockData = {
  mockNotice: "開發測試資料 / 不代表正式名冊",
  currentUserPermission: "admin",
  permissionPrototypeNote: "目前採方案 B：staff / viewer 可看見管理者入口，但會灰色鎖定並提示需管理者權限。",
  adapterNotes: {
    temples: "Web 後台 V2 內部使用 temples；短期正式 V1 runtime 仍對應現有 shrines。",
    templeVisits: "Web 後台 V2 內部使用 temple_visits；短期正式 V1 runtime 仍對應現有 shrine_visits。",
    source: "本檔只供本機 prototype 使用，不寫入正式 Google Sheets。",
    members: "成員名單由使用者提供照片轉錄，僅作開發測試資料，仍需廟方校對後才能作正式名冊。"
  },
  temples: [
    {
      id: "temple-001",
      name: "白沙屯拱天宮",
      alias: "白沙屯媽祖",
      mainGod: "天上聖母",
      address: "苗栗縣通霄鎮白東里",
      phone: "037-xxx-xxx",
      relationStatus: "長期往來",
      latestVisitDate: "2026-05-19",
      enabled: true,
      publicSummary: "多年往來友宮，進香與會香活動互動穩定。",
      internalNote: "重要節慶前建議提前確認接待人數與停車安排。"
    },
    {
      id: "temple-002",
      name: "集慶福德廟",
      alias: "集慶土地公",
      mainGod: "福德正神",
      address: "桃園市中壢區",
      phone: "03-xxx-xxxx",
      relationStatus: "近期互動",
      latestVisitDate: "2026-06-02",
      enabled: true,
      publicSummary: "地方福德信仰友宮，近期有參訪與請帖紀錄。",
      internalNote: "聯絡窗口回覆快速，適合以電話先確認。"
    },
    {
      id: "temple-003",
      name: "大有福德宮",
      alias: "大有土地公",
      mainGod: "福德正神",
      address: "桃園市桃園區",
      phone: "03-xxx-xxxx",
      relationStatus: "請帖往來",
      latestVisitDate: "2026-05-27",
      enabled: true,
      publicSummary: "定期互寄請帖與祝壽資訊。",
      internalNote: "請帖資料需保留紙本照片，未來可加附件功能。"
    },
    {
      id: "temple-004",
      name: "南崁五福宮",
      alias: "五福宮",
      mainGod: "玄壇元帥",
      address: "桃園市蘆竹區",
      phone: "03-xxx-xxxx",
      relationStatus: "待補資料",
      latestVisitDate: "",
      enabled: true,
      publicSummary: "需補齊近年互動紀錄。",
      internalNote: "目前缺主要聯絡人職稱，需廟方確認。"
    },
    {
      id: "temple-005",
      name: "新街仁海宮",
      alias: "仁海宮",
      mainGod: "天上聖母",
      address: "桃園市中壢區",
      phone: "03-xxx-xxxx",
      relationStatus: "資料待確認",
      latestVisitDate: "2026-04-13",
      enabled: false,
      publicSummary: "資料先作為測試樣本，尚未確認是否啟用。",
      internalNote: "停用狀態用來確認列表篩選與標示。"
    }
  ],
  roleTypes: [
    { id: "role-001", name: "主任委員", category: "廟務職務" },
    { id: "role-002", name: "總幹事", category: "廟務職務" },
    { id: "role-003", name: "值年爐主", category: "廟務職務" },
    { id: "role-004", name: "值年副爐主", category: "廟務職務" },
    { id: "role-005", name: "委員", category: "廟務職務" },
    { id: "role-006", name: "監事", category: "廟務職務" },
    { id: "role-007", name: "榮譽主委", category: "廟務職務" },
    { id: "role-008", name: "副主委", category: "廟務職務" },
    { id: "role-009", name: "財務委員", category: "廟務職務" },
    { id: "role-010", name: "總務委員", category: "廟務職務" },
    { id: "role-011", name: "秘書", category: "廟務職務" },
    { id: "role-012", name: "主委", category: "友宮聯絡人" },
    { id: "role-013", name: "總務", category: "友宮聯絡人" },
    { id: "role-014", name: "聯絡窗口", category: "友宮聯絡人" },
    { id: "role-015", name: "admin", category: "系統權限" },
    { id: "role-016", name: "staff", category: "系統權限" },
    { id: "role-017", name: "viewer", category: "系統權限" }
  ],
  contacts: [
    { id: "contact-001", templeId: "temple-001", name: "林先生", role: "聯絡窗口", phone: "09xx-xxx-123", note: "進香活動聯繫", enabled: true },
    { id: "contact-002", templeId: "temple-002", name: "陳小姐", role: "總務", phone: "09xx-xxx-268", note: "請帖與活動確認", enabled: true },
    { id: "contact-003", templeId: "temple-003", name: "黃先生", role: "主委", phone: "09xx-xxx-507", note: "節慶拜訪窗口", enabled: true },
    { id: "contact-004", templeId: "temple-004", name: "待確認", role: "聯絡窗口", phone: "09xx-xxx-xxx", note: "職稱與姓名需補齊", enabled: false }
  ],
  visits: [
    {
      id: "visit-001",
      templeId: "temple-002",
      date: "2026-06-02",
      types: ["參訪", "用餐"],
      peopleCount: 18,
      needsReply: true,
      note: "需回覆接待人數與停車位置。",
      title: "集慶福德廟參訪"
    },
    {
      id: "visit-002",
      templeId: "temple-003",
      date: "2026-05-27",
      types: ["請帖", "祝壽"],
      peopleCount: 2,
      needsReply: false,
      note: "收到祝壽請帖，先登記不發公告。",
      title: "大有福德宮祝壽請帖"
    },
    {
      id: "visit-003",
      templeId: "temple-001",
      date: "2026-05-19",
      types: ["進香", "會香"],
      peopleCount: 42,
      needsReply: true,
      note: "進香團預估一台遊覽車，需安排接待。",
      title: "白沙屯拱天宮會香"
    },
    {
      id: "visit-004",
      templeId: "temple-005",
      date: "2026-04-13",
      types: ["邀請", "聯誼"],
      peopleCount: 6,
      needsReply: true,
      note: "資料待確認，不列入正式公告。",
      title: "仁海宮聯誼邀請"
    }
  ],
  announcements: [
    {
      id: "ann-001",
      title: "白沙屯拱天宮會香接待提醒",
      status: "草稿",
      date: "2026-05-18",
      channels: ["LINE", "FB"],
      public: false,
      relatedVisitId: "visit-003",
      body: "提醒當日接待與動線安排。",
      lineText: "白沙屯拱天宮會香接待提醒：請工作人員依分工準備。"
    },
    {
      id: "ann-002",
      title: "集慶福德廟參訪接待",
      status: "待確認",
      date: "2026-06-01",
      channels: ["LINE", "FB", "VOOM"],
      public: false,
      relatedVisitId: "visit-001",
      body: "集慶福德廟將於 6/2 參訪，請確認接待安排。",
      lineText: "集慶福德廟參訪接待：請接待組留意時間。"
    },
    {
      id: "ann-003",
      title: "端午節服務時間公告",
      status: "可發布",
      date: "2026-06-17",
      channels: ["LINE", "FB", "VOOM"],
      public: true,
      relatedVisitId: "",
      body: "端午期間服務時間照常，歡迎信眾參拜。",
      lineText: "端午期間服務時間照常，歡迎信眾參拜。"
    }
  ],
  announcementLinks: [
    { id: "alink-001", announcementId: "ann-001", targetType: "temple_visit", targetId: "visit-003", note: "示範公告關聯會香紀錄" },
    { id: "alink-002", announcementId: "ann-002", targetType: "temple_visit", targetId: "visit-001", note: "示範公告關聯參訪紀錄" }
  ],
  events: [
    {
      id: "event-001",
      name: "端午節參拜服務",
      date: "2026-06-19",
      type: "節慶",
      location: "中原福德宮",
      public: true,
      linkedAnnouncementId: "ann-003",
      note: "示範活動資料，不代表正式排程。",
      status: "可公開"
    },
    {
      id: "event-002",
      name: "白沙屯拱天宮會香接待",
      date: "2026-05-19",
      type: "會香",
      location: "中原福德宮",
      public: false,
      linkedAnnouncementId: "ann-001",
      note: "由來訪紀錄延伸出的活動雛形。",
      status: "內部確認"
    },
    {
      id: "event-003",
      name: "年度委員會議",
      date: "2026-07-05",
      type: "會議",
      location: "會議室",
      public: false,
      linkedAnnouncementId: "",
      note: "只供畫面流程示範。",
      status: "草稿"
    }
  ],
  publishChannels: [
    { id: "channel-001", name: "LINE", purpose: "LINE 文字公告", enabled: true, officialSendEnabled: false, note: "prototype 只整理文字，不正式發送。" },
    { id: "channel-002", name: "FB", purpose: "Facebook 貼文", enabled: true, officialSendEnabled: false, note: "prototype 只標示可用管道。" },
    { id: "channel-003", name: "VOOM", purpose: "LINE VOOM 貼文", enabled: true, officialSendEnabled: false, note: "prototype 不串接發布 API。" }
  ],
  financeCategories: [
    { id: "fin-cat-001", name: "香油收入", direction: "收入", enabled: true, note: "示範分類，不代表正式帳務科目。" },
    { id: "fin-cat-002", name: "活動支出", direction: "支出", enabled: true, note: "示範分類，不包含帳戶資訊。" },
    { id: "fin-cat-003", name: "修繕支出", direction: "支出", enabled: true, note: "示範分類，不包含真實收據號碼。" }
  ],
  financeRecords: [
    { id: "finance-001", date: "2026-06-10", direction: "收入", category: "香油收入", amountLabel: "金額已遮罩", item: "端午香油收入示範", status: "草稿", note: "不含帳戶、銀行、真實收據號碼。" },
    { id: "finance-002", date: "2026-06-12", direction: "支出", category: "活動支出", amountLabel: "金額已遮罩", item: "活動用品支出示範", status: "待確認", note: "只做可視 prototype，不作正式帳務。" },
    { id: "finance-003", date: "2026-06-14", direction: "支出", category: "修繕支出", amountLabel: "金額已遮罩", item: "設備維修支出示範", status: "草稿", note: "未放入敏感資訊。" }
  ],
  lineQueryLogs: [
    { id: "log-001", time: "2026-06-16 09:12", queryText: "白沙屯", queryType: "友宮查詢", result: "找到資料", matchedName: "白沙屯拱天宮", note: "mock/dev data，不讀正式 line_query_logs。" },
    { id: "log-002", time: "2026-06-16 10:05", queryText: "查來訪 集慶福德廟", queryType: "來訪查詢", result: "找到資料", matchedName: "集慶福德廟參訪", note: "mock/dev data。" },
    { id: "log-003", time: "2026-06-16 11:20", queryText: "不存在的廟名", queryType: "友宮查詢", result: "查無資料", matchedName: "", note: "可進入補資料建議。" }
  ],
  missingDataSuggestions: [
    { id: "missing-001", sourceQuery: "不存在的廟名", type: "查無友宮", status: "待確認", suggestion: "確認是否為新友宮或別名。" },
    { id: "missing-002", sourceQuery: "南崁五福宮", type: "友宮資料不足", status: "待補", suggestion: "補主要聯絡人與近年互動紀錄。" },
    { id: "missing-003", sourceQuery: "活動公告", type: "公告內容確認", status: "待確認", suggestion: "確認是否需要建立公開公告。" }
  ],
  recentActivities: [
    { id: "activity-001", dateLabel: "06/16", title: "白沙屯拱天宮", type: "來訪 / 請帖", targetView: "visits" },
    { id: "activity-002", dateLabel: "06/15", title: "端午活動公告", type: "公告草稿", targetView: "announcements" },
    { id: "activity-003", dateLabel: "06/14", title: "端午節參拜服務", type: "活動更新", targetView: "events" },
    { id: "activity-004", dateLabel: "06/13", title: "南崁五福宮", type: "資料更新", targetView: "temples" }
  ],
  members: [
    {
      id: "member-001",
      name: "林俊澤",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "主任委員",
      systemPermission: "staff",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-002",
      name: "張豐田",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "榮譽主委",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-003",
      name: "郭昌銓",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "副主委",
      systemPermission: "staff",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-004",
      name: "劉興家",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "副主委",
      systemPermission: "staff",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-005",
      name: "黃清源",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "監委",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-006",
      name: "游明錚",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "總幹事",
      systemPermission: "admin",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄。此筆作為目前總幹事 / admin 畫面示範；admin 是系統權限，不綁定單一個人。"
    },
    {
      id: "member-007",
      name: "黎添丁",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "財務委員",
      systemPermission: "staff",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-008",
      name: "李春生",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "總務委員",
      systemPermission: "staff",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-009",
      name: "余桂梅",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "秘書",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-010",
      name: "廖賴桂珍",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "秘書",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-011",
      name: "呂聖通",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-012",
      name: "吳萬看",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-013",
      name: "林瑞瓊",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-014",
      name: "周詠基",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-015",
      name: "葉步坊",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-016",
      name: "顧珠榮",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-017",
      name: "林忠河",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-018",
      name: "林楷原",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-019",
      name: "林芸苓",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-020",
      name: "邱瑞香",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-021",
      name: "洪玉葉",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-022",
      name: "張月華",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-023",
      name: "劉芳梅",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-024",
      name: "謝碧蓮",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-025",
      name: "蘇季英",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-026",
      name: "陳愛卿",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-027",
      name: "陳薪惠",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-028",
      name: "詹秋香",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-029",
      name: "徐嘉慧",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-030",
      name: "呂珍惠",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-031",
      name: "李桂英",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-032",
      name: "呂梅香",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    },
    {
      id: "member-033",
      name: "吳中對",
      phone: "未提供",
      source: "照片轉錄 / 待校對",
      dataNotice: "開發測試資料 / 不代表正式名冊",
      currentUserExample: false,
      committeeGroup: "管委會",
      templeRole: "委員",
      systemPermission: "viewer",
      term: "照片未載明年度",
      enabled: true,
      note: "由使用者提供照片轉錄，待校對後才能作正式名冊。"
    }
  ],
  memberRoleAssignments: [
    { id: "assign-001", memberId: "member-001", roleTypeId: "role-001", startDate: "", endDate: "", active: true, note: "照片轉錄 / 待校對" },
    { id: "assign-002", memberId: "member-006", roleTypeId: "role-002", startDate: "", endDate: "", active: true, note: "總幹事任期示範，照片未載明起訖" },
    { id: "assign-003", memberId: "member-006", roleTypeId: "role-015", startDate: "", endDate: "", active: true, note: "admin 可轉移、增減、停用，不綁定單一個人" },
    { id: "assign-004", memberId: "member-009", roleTypeId: "role-011", startDate: "", endDate: "", active: true, note: "秘書職務示範，照片未載明起訖" },
    { id: "assign-005", memberId: "member-010", roleTypeId: "role-011", startDate: "", endDate: "", active: true, note: "秘書職務示範，照片未載明起訖" },
    { id: "assign-006", memberId: "member-011", roleTypeId: "role-005", startDate: "", endDate: "", active: true, note: "委員職務示範，照片未載明起訖" }
  ]
};
